#BVGraph properties
#Mon Feb 19 16:09:59 CET 2024
arcs=13
avgbitsforblocks=0.083
avgbitsforintervals=0.667
avgbitsforoutdegrees=2.5
avgbitsforreferences=0.75
avgbitsforresiduals=4.167
avgdist=0.083
avgref=0.083
bitsforblocks=1
bitsforintervals=8
bitsforoutdegrees=30
bitsforreferences=9
bitsforresiduals=50
bitsperlink=7.538
bitspernode=8.167
compratio=1.637
compressionflags=
copiedarcs=2
graphclass=it.unimi.dsi.big.webgraph.BVGraph
intervalisedarcs=0
maxrefcount=3
minintervallength=4
nodes=12
residualarcs=11
residualavggap=4.136
residualavgloggap=2.0100596892731315
residualexpstats=4,3,2,2
successoravggap=3.769
successoravgloggap=1.916770115697081
successorexpstats=5,4,2,2
version=0
windowsize=7
zetak=3
