#BVGraph properties
#Mon Feb 19 16:09:57 CET 2024
arcs=13
avgbitsforblocks=0.083
avgbitsforintervals=0.75
avgbitsforoutdegrees=2.667
avgbitsforreferences=1.083
avgbitsforresiduals=4.083
avgdist=0.25
avgref=0.083
bitsforblocks=1
bitsforintervals=9
bitsforoutdegrees=32
bitsforreferences=13
bitsforresiduals=49
bitsperlink=8
bitspernode=8.667
compratio=1.737
compressionflags=
copiedarcs=2
graphclass=it.unimi.dsi.big.webgraph.BVGraph
intervalisedarcs=0
maxrefcount=3
minintervallength=4
nodes=12
residualarcs=11
residualavggap=4.545
residualavgloggap=2.230247395288842
residualexpstats=1,6,2,2
successoravggap=4.115
successoravgloggap=2.103082790018066
successorexpstats=2,7,2,2
version=0
windowsize=7
zetak=3
